name: Dragonix Instagram Bot

on:
  workflow_dispatch:
    inputs:
      post_url:
        description: "Instagram Post / Reel URL"
        required: true

      keyword:
        description: "Trigger keyword in comments"
        required: true

      reply_text:
        description: "Reply message"
        required: true

jobs:
  bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Run Bot
        env:
          INPUT_POST_URL: ${{ inputs.post_url }}
          INPUT_KEYWORD: ${{ inputs.keyword }}
          INPUT_REPLY: ${{ inputs.reply_text }}
        run: python agent.py
