name: Dragonix Instagram Bot

on:
  schedule:
    - cron: "*/5 * * * *"

  workflow_dispatch:
    inputs:
      post_url:
        description: "Instagram Post URL"
        required: false

      keyword:
        description: "Trigger keyword"
        required: false

      comment_reply:
        description: "Comment reply message"
        required: false

      dm_reply:
        description: "DM message"
        required: false

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: pip install requests

      - name: Run Bot
        env:
          INPUT_POST_URL: ${{ inputs.post_url }}
          INPUT_KEYWORD: ${{ inputs.keyword }}
          INPUT_COMMENT_REPLY: ${{ inputs.comment_reply }}
          INPUT_DM_REPLY: ${{ inputs.dm_reply }}
        run: python agent.py
